---
- name: Build project
  command: mvn clean compile
  args:
    chdir: "{{ workspace }}"

- name: Run tests
  command: mvn clean test -Dbrowser.name=chrome -Dselenide.ui.server=http://188.130.251.59:8081/wd/hub allure:report
  args:
    chdir: "{{ workspace }}"