---
- name: Build project
  command: mvn clean compile
  args:
    chdir: "{{ workspace }}"

- name: Run tests
  command:     mvn clean test
    -Dremote.url=http://188.130.251.59:8081/wd/hub
    -Dbrowser.name=chrome
    -Dmaven.compiler.source=21
    -Dmaven.compiler.target=21
    -Dsurefire.useModulePath=false
    allure:report
  args:
    chdir: "{{ workspace }}"